---
# tasks file for ansible-role-libvirt

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ libvirt_log_dir }}"
    mode: 0755
    owner: "{{ libvirt_user }}"
    group: "{{ libvirt_group }}"
    state: directory
  notify: Restart libvirt

- name: Create db directory
  file:
    path: "{{ libvirt_db_dir }}"
    mode: 0755
    owner: "{{ libvirt_user }}"
    group: "{{ libvirt_group }}"
    state: directory
  notify: Restart libvirt

- name: Create libvirt.conf
  template:
    src: libvirt.conf.j2
    dest: "{{ libvirt_conf_file }}"
    validate: echo %s
  notify: Restart libvirt

- name: Start libvirt
  service:
    name: "{{ libvirt_service }}"
    enabled: true
    state: started
